load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "trundle",
    srcs = ["import.cc"],
    hdrs = [
        "trundle.hh",
        "util.hh",
        "import.hh"
    ],
    visibility = ["//visibility:public"],
    copts = ['-std=c++20']
)